### ISSUE TITLE
Improve memory usage

### ISSUE THREAD

**Issue by Krzyhau** [FEZModding/FEZRepacker#14]
Repacker wasn't made with optimal memory usage in mind. Because of this, it creates a lot of dangling resources. Someone should go over the code and figure out a way to make it use less memory.

**Comment by Jenna1337** [comment]
I could not locate any inherently obvious problems with memory usage, but I noticed `ShaderInstancedIndexedPrimitives` can contain a lot of objects at a time. If possible, its loader and whatnot should be changed to iterate through the different items directly from the stream instead of reading all the items into memory and then iterating over each one. There may be other large enumerable objects similar to this, like `Level.Triles` (or `Level.ArtObjects` or `Level.BackgroundPlanes`) but that is the first I noticed.

**Comment by Krzyhau** [comment]
Originally, when I wrote this message, Repacker was storing *every* file in a memory before and after decompression and conversion. That was the biggest concern I had. I solved it a day later with 706c313. I don't necessarily feel like there's a need for a heavier optimization, but I would need to do some testing to see if the memory usage is bearable (also to refresh my brain memory about performance)
